import "@/app/_styles/globals.css";

import Navigation from "@/app/_components/Navigation";
import Logo from "@/app/_components/Logo";

export const metadata = {
  title: "The Wild Oasis",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"bg-primary-950 text-primary-100 min-h-screen"}>
        <header>
          <Logo />
        </header>
        <Navigation />
        <main>{children}</main>
        <footer>Copyright by Ruby</footer>
      </body>
    </html>
  );
}
